language: java
jdk:
  - oraclejdk8
  - oraclejdk11
  - openjdk10
  - openjdk11
os:
  - linux
  - osx
matrix:
  exclude:
    - os: osx
      jdk: oraclejdk8
  include:
    - os: osx
      jdk: oraclejdk8
      osx_image: xcode9.3
